### ISSUE TITLE
Examples of acceptable heuristic analysis

### ISSUE THREAD

**Issue by rt-acumen** [usnistgov/90B-Shall-Statements#24]
ID#33, Section 3.2.2: 

Can CMVP please provide explicit examples or guidelines for an acceptable heuristic analysis? 

Can vendors provide analysis similar to that of the example in FIPS 140-2 IG 7.15?

**Comment by celic** [comment]
Duplicate of #26 right? Either way, same response applies.

**Comment by rt-acumen** [comment]
More or less this is a dupe. Correct.
