### ISSUE TITLE
Boldface all the "shall" and "shall not" in the statements

### ISSUE THREAD

**Issue by richard0378** [usnistgov/90B-Shall-Statements#3]
This makes it more in line with the 90B document itself.

**Comment by celic** [comment]
Noted. I'll try to push this up to the repository to help with readability. 

There are some cases where the statement in the spreadsheet does not exactly match the statement in 90B. We tried to add context when the statement from 90B didn't include it.

**Comment by celic** [comment]
This is done, and uploaded to the repository here.
